### ISSUE TITLE
openstack_cinder_volumes = 0

### ISSUE THREAD

**Issue by dgttm** [Linaro/openstack-exporter#5]
is the cinder volume just listing the admin-owned volumes? those are indeed 0

but I got many volumes in other projects (openstack volume list --all), but the plugin still shows 0 in for openstack_cinder_volumes

**Comment by niedbalski** [comment]
OK, this issue is a candidate to be fixed at 0.0.9 (https://github.com/openstack-exporter/openstack-exporter/issues/12) 

I am closing as the project has been moved to a new location. Please feel free to keep track under https://github.com/openstack-exporter/openstack-exporter
