### ISSUE TITLE
ask: argument in run command

### ISSUE THREAD

**Issue by eveningcafe** [Linaro/openstack-exporter#8]
in
```
./openstack-exporter --os-client-config /etc/openstack/clouds.yml <cloud>
```
please explane what is cloud stand for? i don't get it

**Comment by niedbalski** [comment]
The exporter uses the os-client-config (https://docs.openstack.org/os-client-config/latest/) format, which is indexed by cloud name, this parameter refer to the specific cloud definition on the configuration file for which the exporter should get the metrics from.

Please note that this project has been moved to: https://github.com/openstack-exporter/openstack-exporter 

If you have any question/issue please open a bug under the before mentioned project.

Thanks for contributing!
