### ISSUE TITLE
error query cinder

### ISSUE THREAD

**Issue by eveningcafe** [Linaro/openstack-exporter#9]
i run start command and have errror:
```
invalid status (401): {\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}" source="cinder.go:57"
```
how to fix this? i'm pretty sure my authent was right

**Comment by ralfnova** [comment]
Same issue here

`*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9180 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:9180
> User-Agent: curl/7.58.0
> Accept: */*
>
INFO[0007] Fetching list of services                     source="nova.go:53"
INFO[0007] Fetching domains information                  source="keystone.go:45"
INFO[0007] Fetching floating ips list                    source="neutron.go:47"
INFO[0007] Fetching images list                          source="glance.go:39"
INFO[0007] Fetching volumes info                         source="cinder.go:54"
ERRO[0007] invalid status (401): {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}  source="cinder.go:57"
INFO[0007] Fetching services state information           source="cinder.go:60"
ERRO[0007] invalid status (401): {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}  source="cinder.go:63"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x82827d]

goroutine 47 [running]:
main.(*CinderExporter).Collect(0xc0001865c0, 0xc00008b860)
        /app/cinder.go:66 +0x1dd
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x193
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:526 +0xe23
* Empty reply from server
* Connection #0 to host localhost left intact
`

**Comment by ivveh** [comment]
I've got the same error as well....
I can also confirm my settings on authentication are correct. Disabling cinder with the --disable-service.volume is a work-around but you won't get cinder metrics.

**Comment by niedbalski** [comment]
Could you check if this problem is still reproduced with the 0.0.8 release (https://github.com/openstack-exporter/openstack-exporter/releases/tag/v0.0.8)

Please also note that this project has been moved to: https://github.com/openstack-exporter/openstack-exporter

Thanks!

**Comment by niedbalski** [comment]
Feel free to open a new issue if this problem still occurs at (https://github.com/openstack-exporter/openstack-exporter)
